version: '3.7'

services:
  auth: 
    container_name: auth
    image: ramzi611/barbershop-auth:latest
    hostname: auth
    ports:
      - 3001:3001
    environment: 
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=barbershopdb
      - JWT_SECRET=qm{[--èrlsdkhjfmqoujhfgpquighkjqrg5678324*/67824*/95sdqkljhg
      - PRODUCTION=true
      - DB_USER=barbershopuser
      - DB_PASSWD=barbershoppasswd
    command: npx nx run auth-micro:serve:production
    depends_on:
      - database
  posts: 
    container_name: posts
    image: ramzi611/barbershop-posts:latest
    hostname: posts
    ports:
      - 3002:3002
    environment:
      - PRODUCTION=true
      - DB_USER=barbershopuser
      - DB_PASSWD=barbershoppasswd
      - PORT=3002
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=barbershopdb
    command: npx nx run posts-micro:serve:production
    depends_on:
      - auth
  gateway: 
    container_name: gateway
    image: ramzi611/barbershop-gateway:latest
    hostname: gateway
    ports:
      - 3000:3000
    environment: 
      - PRODUCTION=true
      - JWT_SECRET=qm{[--èrlsdkhjfmqoujhfgpquighkjqrg5678324*/67824*/95sdqkljhg
      - POSTS_MICRO_PORT=3002
      - POSTS_MICRO_HOST=posts
      - ENV AUTH_MICRO_PORT=3001
      - AUTH_MICRO_HOST=auth
    command: npx nx run gateway-api:serve:production
    depends_on:
      - posts
  database:
    image: postgres:14.1-alpine
    hostname: database
    environment:
      - POSTGRES_USER=barbershopuser
      - POSTGRES_PASSWORD=barbershoppasswd
      - POSTGRES_DB=barbershopdb
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
