apiVersion: apps/v1
kind: Deployment
metadata:
  name: barbershop-authentication
  labels:
    app: auth
spec:
  strategy: 
    type: shadow
    shadow:
      source:
        deployment: barbershop-authentication
  replicas: {{ .Values.authenticaion.deployment.replicas }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      annotations:
        prometheus.io/port: {{ .Values.authentication.service.port }}
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: ramzi611/barbershop-auth:latest
        ports:
        - containerPort: {{ .Values.authentication.service.port }}
        env:
          - name: PRODUCTION
            value: true
          - name: JWT_SECRET
            value: {{ .Values.authentication.deployment.jwt }}
          - name: DB_HOST
            value: {{ .Values.authentication.deployment.DB_HOST}}
          - name: DB_PORT
            value: {{ .Values.authentication.deployment.DB_PORT}}
          - name: DB_NAME
            value: {{ .Values.authentication.deployment.DB_NAME}}
          - name: DB_USER
            value: {{ .Values.authentication.deployment.DB_USER}}
          - name: DB_PASSWD
            value: {{ .Values.authentication.deployment.DB_PASSWD}}