apiVersion: apps/v1
kind: Deployment
metadata:
  name: barbershop-gateway
  labels:
    app: barbershop-gateway
spec:
  strategy: 
    type: shadow
    shadow:
      source:
        deployment: barbershop-gateway
  replicas: {{ .Values.gateway.deployment.replicas }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway-container
        image: ramzi611/barbershop-gateway
        ports:
        - containerPort: 3000
        env:
          - name: PRODUCTION
            value: true
          - name: JWT_SECRET
            value: {{ .Values.gateway.deployment.jwt }}
          - name: POST_MICRO_HOST
            value: {{ .Values.gateway.deployment.POST_MICRO_HOST }}
          - name: POST_MICRO_PORT
            value: {{ .Values.gateway.deployment.POST_MICRO_PORT }}
          - name: AUTH_MICRO_HOST
            value: {{ .Values.gateway.deployment.AUTH_MICRO_HOST }}
          - name: AUTH_MICRO_PORT
            value: {{ .Values.gateway.deployment.POST_MICRO_HOST }}